global:
  namespace: countries-app

countries-service:
  replicaCount: 1
  image:
    repository: helm-umbrella-chart-countries-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

client-service:
  replicaCount: 1
  image:
    repository: helm-umbrella-chart-client-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: countries.local
        paths:
          - path: /
            pathType: Prefix
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    - name: COUNTRIES_SERVICE_URL
      value: "http://helm-umbrella-chart-countries-service:8080/countries"